# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 22:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170201_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='boycottuser',
            name='zip',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Please enter a valid zipcode')]),
        ),
    ]
