# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
            preserve_default=False,
        ),
    ]
