# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='choices',
            field=models.ManyToManyField(blank=True, to='polls.Choice'),
        ),
    ]
