# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='color',
        ),
        migrations.AddField(
            model_name='poll',
            name='color',
            field=models.CharField(default='#ffffff,#ffffff', max_length=200),
            preserve_default=False,
        ),
    ]
