# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 07:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boycott',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('reason', models.CharField(max_length=500, verbose_name='Why are you boycotting?')),
                ('boycotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boycotted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Entity being boycotted')),
                ('zip', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Please enter a valid zipcode')])),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('tag', models.IntegerField(choices=[(1, 'Other'), (2, 'People'), (3, 'Sports'), (4, 'Buisnesses'), (5, 'International'), (6, 'Local')], default=1)),
                ('boycotts', models.ManyToManyField(blank=True, to='boycotted.Boycott')),
            ],
        ),
        migrations.CreateModel(
            name='DirtyFilterModelIFeelGuiltyAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(choices=[(0, 'All'), (1, 'Other'), (2, 'People'), (3, 'Sports'), (4, 'Buisnesses'), (5, 'International'), (6, 'Local')], default=0)),
                ('sort', models.IntegerField(choices=[(0, 'Most Boycotted'), (1, 'Alphabetical Order'), (2, 'Most Comments'), (3, 'Most Recent')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='boycott',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boycotted.Boycotted'),
        ),
    ]
