# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boycotted', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirtyFilterModelIFeelGuiltyAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(choices=[(0, 'All'), (1, 'Other'), (2, 'People'), (3, 'Sports'), (4, 'Buisnesses'), (5, 'International'), (6, 'Local')], default=0)),
                ('sort', models.IntegerField(choices=[(0, 'Most Boycotted'), (1, 'Alphabetical Order'), (2, 'Most Recent')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='boycotted',
            name='tag',
            field=models.IntegerField(choices=[(1, 'Other'), (2, 'People'), (3, 'Sports'), (4, 'Buisnesses'), (5, 'International'), (6, 'Local')], default=1),
        ),
    ]
