# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boycotted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boycott',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='boycotted',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
