# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boycotted', '0002_auto_20170306_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='boycotted',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dirtyfiltermodelifeelguiltyabout',
            name='sort',
            field=models.IntegerField(choices=[(1, 'Most Boycotted'), (2, 'Alphabetical Order'), (3, 'Most Recent')], default=0),
        ),
        migrations.AlterField(
            model_name='dirtyfiltermodelifeelguiltyabout',
            name='tag',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'Other'), (3, 'People'), (4, 'Sports'), (5, 'Buisnesses'), (6, 'International'), (7, 'Local')], default=0),
        ),
    ]
